on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run Spring Boot application
        run: nohup java -jar build/libs/your-app.jar &

      - name: Install Bruno CLI
        run: |
          npm install -g @usebruno/cli

      - name: Run Bruno tests
        run: |
          bruno run bruno/collection.json --env apiUrl=localhost:8080/api --reporters junit --output-report results.xml

      # Step 7: Upload test results as an artifact (JUnit report format)
      - name: Publish test results
        uses: actions/upload-artifact@v3
        with:
          name: bruno-test-report
          path: bruno/results.xml
