on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run Spring Boot application
        run: nohup java -jar bootstrap/build/libs/bootstrap.jar &

      - name: Install Bruno CLI
        run: |
          npm install -g @usebruno/cli

      - name: Run Bruno tests
        run: |
          ls
          cd bruno/
          bru run --env local --reporter-junit junit --output results.xml

      - name: Publish test results
        uses: actions/upload-artifact@v3
        with:
          name: bruno-test-report
          path: results.xml
