name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: bootstrap-jar
          path: bootstrap/build/libs/bootstrap.jar

  start:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download JAR file
        uses: actions/download-artifact@v4
        with:
          name: bootstrap-jar

      - name: Run Spring Boot application
        run: |
          nohup java -jar bootstrap.jar &

  bruno_tests:
    runs-on: ubuntu-latest
    needs: start
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Bruno CLI
        run: |
          npm install -g @usebruno/cli

      - name: Run Bruno tests
        run: |
          cd bruno
          bru run --env local --output results.xml

      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: bruno-test-report
          path: bruno/results.xml

  sign:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GnuPG
        run: sudo apt-get install -y gnupg

      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --import --batch --passphrase "$GPG_PASSPHRASE"

      - name: Download JAR file
        uses: actions/download-artifact@v4
        with:
          name: bootstrap-jar

      - name: Sign the JAR file
        run: |
          gpg --batch --yes --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback --detach-sign --armor bootstrap.jar
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Upload signature artifact
        uses: actions/upload-artifact@v4
        with:
          name: bootstrap-signature
          path: bootstrap.jar.asc
